<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MeusDecks.cs" />
    <Compile Remove="MeusDecks.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="MeusDecks.resx" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MySql.Data">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\MySQL\MySQL Connector NET 26.7\MySql.Data.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Form_CriarConta.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>